### ISSUE TITLE
Code Problem

### ISSUE THREAD

**Issue by wztws** [hust-linyi/CAT-Net#5]
Traceback (most recent call last):
  File "C:\Users\anaconda3\envs\torch\lib\site-packages\sacred\experiment.py", line 312, in run_commandline
    return self.run(
  File "C:\Users\anaconda3\envs\torch\lib\site-packages\sacred\experiment.py", line 276, in run
    run()
  File "C:\Users\anaconda3\envs\torch\lib\site-packages\sacred\run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "C:\Users\anaconda3\envs\torch\lib\site-packages\sacred\config\captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "train.py", line 55, in main
    model = FewShotSeg()
  File "C:\work\CAT-Net\models\fewshot.py", line 22, in __init__
    self.conv_fusion = nn.Conv2d(self.encoder.output_dim + 1, self.encoder.output_dim, kernel_size=1)
  File "C:\Users\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Res101Encoder' object has no attribute 'output_dim'

May I ask if there is a problem with the code? I run it and it reports an error, what can I do to fix it?

**Comment by CYF2000127** [comment]
Thanks for your attention, we have fixed the bug
